title: Community Resources
description: Resources for Students Navigating Higher Education
remote_theme: pmarsceill/just-the-docs
color_scheme: usparc
just_the_docs:
  collapsible_nav: true
  footer_content: ""
baseurl: "./"
